Add LoggerServlet
clusterbench/clusterbench pull request #528
Opened 2024-11-13 16:03 UTC by tommaso-borgato

Add a simple servlet named `LoggerServlet` which just prints a customized message in the server.log file, e.g.:
```
2024-11-13 16:05:00,158 INFO  [org.jboss.test.clusterbench.web.debug.LoggerServlet] (default task-1) CLUSTERING_LIFECYCLE_MARKER: ping
```

2024-11-13 16:08 UTC, rhusar requested changes
Needs changed. Also missing updating README.

2024-11-13 16:08 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +        response.setContentType("text/html");
This is no HTML :)

2024-11-13 16:08 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +        out.println("OK");
Don't some output Success? I think we should standardize this.

2024-11-13 16:08 UTC, rhusar commented on integration-tests/wildfly/src/test/java/org/jboss/test/clusterbench/it/wildfly/LoggerServletIT.java
> +	 * Verifies jboss.node.name is obtainable from debug servlet.
This is unrelated.

2024-11-13 16:08 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +@WebServlet("/api/log")
Hm, why /api? I think just `/log` is enough.

2024-11-13 16:08 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +                type == null ? "CLUSTERING_LIFECYCLE_MARKER" : type,
What is CLUSTERING_LIFECYCLE_MARKER? Is this somthing that you are already using in existing tests?

2024-11-13 16:09 UTC, tommaso-borgato commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +                type == null ? "CLUSTERING_LIFECYCLE_MARKER" : type,
Yes

2024-11-13 16:16 UTC, tommaso-borgato commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +        out.println("OK");
I didn't find any, shall I change it to "Success"?

2024-11-13 16:54 UTC, rhusar requested changes

2024-11-13 16:54 UTC, rhusar commented on integration-tests/wildfly/src/test/java/org/jboss/test/clusterbench/it/wildfly/LoggerServletIT.java
> +			HttpGet httpGet = new HttpGet("http://localhost:8080/clusterbench/api/log");
This test now fails :-)

2024-11-13 16:54 UTC, rhusar commented
Also, please link the issue in the commit (and here) - https://github.com/clusterbench/clusterbench/issues/397

2024-11-14 09:46 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +        out.println("OK");
OK so it's AverageSystemLoadServlet and it's response is

        response.getWriter().print("DONE");

Sigh,...

2024-11-14 09:53 UTC, rhusar requested changes

2024-11-14 09:53 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +        out.println("OK");
OK so this is by no means standard, but we don't want an empty response as people might think that nothing happened. "Success" as plain text in the body is an informal practice rather than a standard, and it’s generally better to return more structured data if a response body is needed. So any objection to changing this to "Success"?

2024-11-14 09:53 UTC, rhusar commented on integration-tests/wildfly/src/test/java/org/jboss/test/clusterbench/it/wildfly/LoggerServletIT.java
> +				assertEquals(200, response.getStatusLine().getStatusCode());
Also check response body here == Success.

2024-11-14 09:53 UTC, rhusar commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +                type == null ? "CLUSTERING_LIFECYCLE_MARKER" : type,
I am sorry but I still miss the purpose of this. The `String.format("%s: %s", type, msg)` should be done on the client, this should just output whatever was received. There is no reason to complicate the logic here.

This should be as simple as calling:

http://localhost:8080/clusterbench/log?msg=CLUSTERING_LIFECYCLE_MARKER:+shutdown

Or am I missing something?

2024-11-14 12:08 UTC, tommaso-borgato commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +        out.println("OK");
none! changed

2024-11-14 12:10 UTC, tommaso-borgato commented on clusterbench-ee10-web/src/main/java/org/jboss/test/clusterbench/web/debug/LoggerServlet.java
> +                type == null ? "CLUSTERING_LIFECYCLE_MARKER" : type,
Actually it is, these are just defaults .... shall we remove them?

2024-11-14 12:17 UTC, tommaso-borgato commented on integration-tests/wildfly/src/test/java/org/jboss/test/clusterbench/it/wildfly/LoggerServletIT.java
> +				assertEquals(200, response.getStatusLine().getStatusCode());
Done!

2024-11-19 08:06 UTC, tommaso-borgato commented
@rhusar can we merge this one?

2024-11-19 10:00 UTC, rhusar commented
> @rhusar can we merge this one?

Do you really insist on the arbitrary String that's printed out as a 'ping'? Specifically: 

    "CLUSTERING_LIFECYCLE_MARKER: ping"

If you insist that's fine, but it's very arbitrary, and as I pointed out here https://github.com/clusterbench/clusterbench/pull/528#discussion_r1841895902 this should really be part of the client.

2024-11-19 10:00 UTC, rhusar commented
Also, still missing readme and tomcat test - but I can do that post merge quickly, so no worries about that.

2024-11-21 15:38 UTC, rhusar approved these changes
LGTM

2024-11-21 15:43 UTC, merged